### ISSUE TITLE
not able get records from the table.

### ISSUE THREAD

**Issue by mevadadhruv** [memiiso/debezium-server-iceberg#341]
hi @ismailsimsek ,
so we are using debezium as a part of our architecture where we are using Oracle db as a source and destination as a dremio.
in that we are trying to access the initial and incremental load of the table from the database through CDC events. the process which we are following is 
oracle -> aws iceberg tables -> aws s3 bucket (where data and metadata are stored) -> dremio (configured iceberg tables and s3 bucket), for this we have provided parameters (application.properties) for which I have attached a file for better understanding.
now the problem which we are facing is that, we are not able to get any of the data from the table. we are just getting the metadata of that in dremio and in dremio I have configured both 
still i'm not able to get data from any of it.
[application_properties.txt](https://github.com/user-attachments/files/15762595/application_properties.txt)
![image](https://github.com/memiiso/debezium-server-iceberg/assets/109581220/cab0aa17-68a9-44a6-9ca5-d86c95f12be9)

**Comment by ismailsimsek** [comment]
Are you able to read the table using AWS glue? Could you compare the glue table path and S3 path? Recently there were issue on that #320

**Comment by mevadadhruv** [comment]
hi @ismailsimsek ,
thanks for quick response, but we are getting data as above image, but we don't want that way, we expect data as a below attachment.
Thank you,
Dhruv
![image](https://github.com/memiiso/debezium-server-iceberg/assets/109581220/708f98c7-f67e-443f-9e4c-546621ab8fa0)

**Comment by ismailsimsek** [comment]
@mevadadhruv please check following configs. make sure [include exclude list ](https://debezium.io/documentation/reference/stable/connectors/oracle.html#oracle-property-table-include-list) settings are containing the schema you want to replicate. 
```
debezium.source.table.include.list=schemaname.tablename
```

the table you are querying is just additional metadata table created by following config. since you are able to query it that means everything is working as expected. 

```
debezium.source.include.schema.changes=true
```

**Comment by mevadadhruv** [comment]
hi @ismailsimsek , 
    if you could please check our application.properties, in that you will find out that we already provided that parameters.
Thank you,
Dhruv Mevada

**Comment by ismailsimsek** [comment]
@mevadadhruv please check the value you are using `schemaname.tablename`.  i recommend trying with regexp `*`

**Comment by ismailsimsek** [comment]
@mevadadhruv  could you attach debezium logs too?

**Comment by ismailsimsek** [comment]
@GOVINDARAMTEKKAR97  i recommend checking debezium-server logs, then you can see what is actually happening. 
having schema changes doesn't means debezium is replicating the table.

**Comment by GOVINDARAMTEKKAR97** [comment]
Hi @ismailsimsek  ok  if I do ./run.sh i will showing the process which parameter need to set on application.properties so I can see details log, can you provide me please.
# Oracle connector configuration
debezium.source.connector.class=io.debezium.connector.oracle.OracleConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=0
debezium.source.database.hostname=localhost
debezium.source.database.port=1521
debezium.source.database.user=user
debezium.source.database.password=password$1234
debezium.source.database.dbname=db
debezium.source.database.pdb.name=pdb
debezium.source.table.include.list=schemaname.tablename
snapshot.include.collection.list=schemaname.tablename
#debezium.source.schema.include.list=schemaname
#debezium.source.database.connection.adapter=logminer
#debezium.source.snapshot.mode=schema_only
#debezium.source.database.schema=
#################################################################################
 
debezium.source.include.schema.changes=true
# Uncomment if using a PDB
debezium.source.topic.prefix=tutorial
# If you have a specific start SCN, set it here. If not, let it auto-generate.
#debezium.source.start.scn=default
# Uncomment if you have a specific end SCN, otherwise, omit it
#debezium.source.end.scn=null
# Optional table filters
#debezium.source.table.include.list=your-schema.your-table
#debezium.source.include.schema.changes=true
#debezium.source.replica.identity.autoset.values=lot:FULL
 
##########################################################################################
# Sink type configuration
debezium.sink.type=iceberg
debezium.sink.iceberg.table-prefix=debeziumcdc_
debezium.sink.iceberg.upsert=false
debezium.sink.iceberg.upsert-keep-deletes=false
debezium.sink.iceberg.write.format.default=parquet
debezium.sink.iceberg.catalog-name=iceberg
#debezium.sink.iceberg.table-name=tablename
############################################################################################
# Enable event schemas
debezium.format.value.schemas.enable=true
debezium.format.key.schemas.enable=true
debezium.format.value=json
debezium.format.key=json
 
###############################################################################################
# Unwrap messages
debezium.transforms=unwrap
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.add.fields=op,table,source.ts_ms,db
debezium.transforms.unwrap.delete.handling.mode=rewrite
debezium.transforms.unwrap.drop.tombstones=true
 
############################################################################################
# Logging configuration
quarkus.log.level=INFO
quarkus.log.console.json=false
quarkus.log.category."org.apache.hadoop".level=WARN
quarkus.log.category."org.apache.parquet".level=WARN
quarkus.log.category."org.eclipse.jetty".level=WARN
 
##############################################################################################
 
debezium.source.log.mining.scn.gap.detection.gap.size.min=10000
debezium.source.log.mining.scn.gap.detection.time.interval.max.ms=300000
 
# Advanced consuming configuration
#debezium.source.offset.storage=io.debezium.server.iceberg.offset.IcebergOffsetBackingStore
#debezium.source.offset.storage.iceberg.table-name=debezium_offset_storage_custom_table
debezium.source.schema.history.internal=io.debezium.server.iceberg.history.IcebergSchemaHistory
debezium.source.schema.history.internal.iceberg.table-name=debezium_database_history_storage_test
 
##################################################################################################
# Batch configuration
debezium.sink.batch.batch-size-wait=MaxBatchSizeWait
debezium.sink.batch.batch-size-wait.max-wait-ms=180000
debezium.sink.batch.batch-size-wait.wait-interval-ms=120000
debezium.sink.batch.metrics.snapshot-mbean=debezium.oracle:type=connector-metrics,context=snapshot,server=testc
debezium.sink.batch.metrics.streaming-mbean=debezium.oracle:type=connector-metrics,context=streaming,server=testc
debezium.source.max.batch.size=15
debezium.source.max.queue.size=45
 
# S3 File IO configuration
debezium.sink.iceberg.io-impl=org.apache.iceberg.aws.s3.S3FileIO
debezium.sink.iceberg.s3.access-key-id=
debezium.sink.iceberg.s3.secret-access-key=
debezium.sink.iceberg.warehouse=s3://path
debezium.sink.iceberg.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
AWS_REGION=eu-west-1
 
logging.level.io.debezium=DEBUG
logging.level.org.apache.iceberg=DEBUG

we are using this things in applicaion.properties file

**Comment by mevadadhruv** [comment]
hello @ismailsimsek Good Morning, and also like if possible than can we connect for this through ZULIP or any bridge so you can get better understanding on this.
